### ISSUE TITLE
Add options time to save in cache

### ISSUE THREAD

**Issue by RuslanMelnychenko** [telegrambotindonesia/WizardScene#1]
Please add option for set save time of scene in cache
https://github.com/telegrambotindonesia/WizardScene/blob/v2/index.ts#L37

**Comment by butthx** [comment]
Hi, Thank you for the first Issue. 
I will try to add the option for cache time in the future update _(i can't promise when is it)_. 

It would be great if you do a change and pull request on the source code, that way I can quickly update the version in google script.

Best regards
~ Butthx

**Comment by butthx** [comment]
Hi, I have a good news for you. The project has been updated (#2 ). So don't forget to try it and give a feedback. Thanks you.

Best regards
~ Butthx
